<a href="https://colab.research.google.com/github/bhadreshpsavani/ExploringDataScience/blob/master/DataScience_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

## Check Normal List Size:

In [ ]:
# Input
lst = [5, 10, 0, 200]
# Expected Output:
# [10, 15, 5, 205]  
lst

[5, 10, 0, 200]

In [ ]:
# Input
lst = [1, 2, 3, 'text', True, 3+2j]
# Expected output:
# A pure homogeneous vector, all 6 elements converted into a single datatype. 
for i in lst:
  print(i, type(i))

1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
text <class 'str'>
True <class 'bool'>
(3+2j) <class 'complex'>


In [ ]:
import sys
# Input
lst = [56, 45, 12, 6] 
# Expected output:
# 16 
sys.getsizeof(lst)

96

## Numpy Operations

In [ ]:
lst = [5, 10, 0, 200] 
arr = np.array(lst)
print(arr + 5)
# Output:
# [10, 15, 5, 205] 

[ 10  15   5 205]


In [ ]:
lst = [1, 2, 3, 'text', True, 3+2j] 
arr = np.array(lst)
print(type(arr[0]),type(arr[4]), type(arr[5]))
# Output:
# <class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'> 

<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'>


In [ ]:
lst = [56, 45, 12, 6]
arr = np.array(lst)
print(arr.nbytes)
# Output:
# 16 

32


## Numpy Array Creation:

In [ ]:
arr = np.array([2,5,6,8], dtype = int)
print(arr)
# [2 5 6 8]
print(type(arr))
# class 'numpy.ndarray'
print(np.result_type(arr))
# int32 
 


[2 5 6 8]
<class 'numpy.ndarray'>
int64


In [ ]:
 ''' Creation of an array with step size 1.33 between 0 - 10 '''
print(np.arange(0, 10, 1.33, dtype = np.float64))
# [ 0.    1.33  2.66  3.99  5.32  6.65  7.98  9.31]
# arange() gives uncertain number of values based on steps
# Hence, we use linspace, which asks for total number of values 
''' Creation of an array with total 5 values between 0 - 160 '''
print(np.linspace(0, 160, 5, dtype = np.float64))
# [   0.   40.   80.  120.  160.] 

[0.   1.33 2.66 3.99 5.32 6.65 7.98 9.31]
[  0.  40.  80. 120. 160.]


## Numpy Matrix Creation:

In [ ]:
''' Method I: Using array and reshape to convert array into matrix '''
print(np.array([5,6,8,45,12,52]).reshape(2,3))
# [[ 5  6  8]
#  [45 12 52]]
''' Method II: Using matrix function '''
print(np.matrix([[1,2],
                [3,4]]))
# [[1 2]
#  [3 4]]
''' Method III: Using misc. functions '''
print(np.eye(3)) # Identity matrix
# [[ 1.  0.  0.]
#  [ 0.  1.  0.]
#  [ 0.  0.  1.]]
print( np.zeros( (4,3) ) )
# [[ 0.  0.  0.]
#  [ 0.  0.  0.]
#  [ 0.  0.  0.]
#  [ 0.  0.  0.]]
print(np.ones( (3,3), dtype = np.float64 ))
# [[ 1.  1.  1.]
#  [ 1.  1.  1.]
#  [ 1.  1.  1.]]

[[ 5  6  8]
 [45 12 52]]
[[1 2]
 [3 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Excercise:

In [ ]:
arr1 = np.array([25, 56, 12, 85, 34, 75])
arr2 = np.array([42, 3, 86, 32, 856, 46])
arr1.astype(np.complex)
Narr = np.random.rand(arr1.shape[-1])
print(arr1)
print(np.result_type(arr1))

[25 56 12 85 34 75]
int64


In [ ]:
arr1_mat = arr1.reshape((2, 3))
print(arr1_mat)
arr2_mat = arr2.reshape((2, 3))
print(arr2_mat)
print((arr1_mat*arr1_mat-arr2_mat*arr2_mat)/(arr1_mat - arr2_mat))

[[25 56 12]
 [85 34 75]]
[[ 42   3  86]
 [ 32 856  46]]
[[ 67.  59.  98.]
 [117. 890. 121.]]


In [ ]:
arr1 = np.ones(10)
arr2 = np.arange(10, dtype=np.float64)
arr3 = arr1+arr2
print(np.result_type(arr1))
print(np.result_type(arr2))

float64
float64


In [ ]:
arr = np.arange(4)
print(arr.shape)

(4,)


In [ ]:
arr = np.arange(4).reshape(4, -1)
print(arr.shape)

(4, 1)


In [8]:
# Create a 4 x 4 matrix and add values 4,5,6 above the parent diagonal.
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])
np.diag([4,5,6], 1)

array([[0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6],
       [0, 0, 0, 0]])

In [9]:
# Given a Numpy array arr = np.arange(11), negate all the elements between 6 and 10.
arr = np.arange(11)
print(arr)
np.where((arr>6) & (arr<10), arr*-1, arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 0,  1,  2,  3,  4,  5,  6, -7, -8, -9, 10])

In [10]:
"""
Given a matrix mat and an array arr, for each row of the matrix if elements of 
Column 1 are equal to the corresponding element of the array, 
then print the corresponding value of Column 2 of the matrix.
"""
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl']) 
mat[np.where(mat[:,0]==arr)][:,1]

array(['A', 'C'], dtype='<U3')

In [13]:
#  Given a matrix mat, sort it by the second column.
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])
print(mat[mat[:,1].argsort()])

[[ 5  4  2]
 [56 12  4]
 [ 1 21  3]]


In [15]:
# Given an array arr, find the top 4 maximum values.
arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])
arr[np.argpartition(arr, -4)[-4:]] # Note: Argpartition don't return array in sorted manner

array([ 45,  50, 590,  90])

In [16]:
# Find the nearest number from the given number in an array.
arr = np.array([10,55,22,3,6,44,9,54])
nearest_to = 50
arr[np.abs(arr-nearest_to).argmin()]

54